#!/usr/local/bin/python3

# -*- coding: utf-8 -*-

import sys

from minipoker.main import main
from minipoker.splash import Splash, WorldSelector


sp = Splash()
name = sp.name()
ws = WorldSelector(name)
world = ws.menu()

main(name, world)
